/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as Nehub53ff1f11RouteImport } from './routes/nehub-53ff1f11'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as SuiviCommandeRouteImport } from './routes/suivi-commande'
import { Route as FactureIdRouteImport } from './routes/facture.$id'
import { Route as Nehub53ff1f11IndexRouteImport } from './routes/nehub-53ff1f11.index'
import { Route as Nehub53ff1f11AvisRouteImport } from './routes/nehub-53ff1f11.avis'
import { Route as Nehub53ff1f11CategoriesRouteImport } from './routes/nehub-53ff1f11.categories'
import { Route as Nehub53ff1f11CodesPromoRouteImport } from './routes/nehub-53ff1f11.codes-promo'
import { Route as Nehub53ff1f11ComptabiliteRouteImport } from './routes/nehub-53ff1f11.comptabilite'
import { Route as Nehub53ff1f11DepensesRouteImport } from './routes/nehub-53ff1f11.depenses'
import { Route as Nehub53ff1f11ParametresRouteImport } from './routes/nehub-53ff1f11.parametres'
import { Route as Nehub53ff1f11PromotionsRouteImport } from './routes/nehub-53ff1f11.promotions'
import { Route as Nehub53ff1f11StocksRouteImport } from './routes/nehub-53ff1f11.stocks'
import { Route as Nehub53ff1f11VentesHorsSiteRouteImport } from './routes/nehub-53ff1f11.ventes-hors-site'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as Nehub53ff1f11CommandesIndexRouteImport } from './routes/nehub-53ff1f11.commandes.index'
import { Route as Nehub53ff1f11CommandesIdRouteImport } from './routes/nehub-53ff1f11.commandes.$id'
import { Route as Nehub53ff1f11ProduitsIndexRouteImport } from './routes/nehub-53ff1f11.produits.index'
import { Route as Nehub53ff1f11ProduitsIdRouteImport } from './routes/nehub-53ff1f11.produits.$id'
import { Route as Nehub53ff1f11ProduitsNouveauRouteImport } from './routes/nehub-53ff1f11.produits.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const Nehub53ff1f11Route = Nehub53ff1f11RouteImport.update({
  id: '/nehub-53ff1f11',
  path: '/nehub-53ff1f11',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviCommandeRoute = SuiviCommandeRouteImport.update({
  id: '/suivi-commande',
  path: '/suivi-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const FactureIdRoute = FactureIdRouteImport.update({
  id: '/facture/$id',
  path: '/facture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Nehub53ff1f11IndexRoute = Nehub53ff1f11IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11AvisRoute = Nehub53ff1f11AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11CategoriesRoute = Nehub53ff1f11CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11CodesPromoRoute = Nehub53ff1f11CodesPromoRouteImport.update({
  id: '/codes-promo',
  path: '/codes-promo',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11ComptabiliteRoute =
  Nehub53ff1f11ComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)
const Nehub53ff1f11DepensesRoute = Nehub53ff1f11DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11ParametresRoute = Nehub53ff1f11ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11PromotionsRoute = Nehub53ff1f11PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11StocksRoute = Nehub53ff1f11StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11VentesHorsSiteRoute =
  Nehub53ff1f11VentesHorsSiteRouteImport.update({
    id: '/ventes-hors-site',
    path: '/ventes-hors-site',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Nehub53ff1f11CommandesIndexRoute =
  Nehub53ff1f11CommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)
const Nehub53ff1f11CommandesIdRoute =
  Nehub53ff1f11CommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)
const Nehub53ff1f11ProduitsIndexRoute =
  Nehub53ff1f11ProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)
const Nehub53ff1f11ProduitsIdRoute = Nehub53ff1f11ProduitsIdRouteImport.update({
  id: '/produits/$id',
  path: '/produits/$id',
  getParentRoute: () => Nehub53ff1f11Route,
} as any)
const Nehub53ff1f11ProduitsNouveauRoute =
  Nehub53ff1f11ProduitsNouveauRouteImport.update({
    id: '/produits/nouveau',
    path: '/produits/nouveau',
    getParentRoute: () => Nehub53ff1f11Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nehub-53ff1f11': typeof Nehub53ff1f11RouteWithChildren
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/facture/$id': typeof FactureIdRoute
  '/nehub-53ff1f11/avis': typeof Nehub53ff1f11AvisRoute
  '/nehub-53ff1f11/categories': typeof Nehub53ff1f11CategoriesRoute
  '/nehub-53ff1f11/codes-promo': typeof Nehub53ff1f11CodesPromoRoute
  '/nehub-53ff1f11/comptabilite': typeof Nehub53ff1f11ComptabiliteRoute
  '/nehub-53ff1f11/depenses': typeof Nehub53ff1f11DepensesRoute
  '/nehub-53ff1f11/parametres': typeof Nehub53ff1f11ParametresRoute
  '/nehub-53ff1f11/promotions': typeof Nehub53ff1f11PromotionsRoute
  '/nehub-53ff1f11/stocks': typeof Nehub53ff1f11StocksRoute
  '/nehub-53ff1f11/ventes-hors-site': typeof Nehub53ff1f11VentesHorsSiteRoute
  '/produit/$id': typeof ProduitIdRoute
  '/nehub-53ff1f11/': typeof Nehub53ff1f11IndexRoute
  '/nehub-53ff1f11/commandes/$id': typeof Nehub53ff1f11CommandesIdRoute
  '/nehub-53ff1f11/produits/$id': typeof Nehub53ff1f11ProduitsIdRoute
  '/nehub-53ff1f11/produits/nouveau': typeof Nehub53ff1f11ProduitsNouveauRoute
  '/nehub-53ff1f11/commandes/': typeof Nehub53ff1f11CommandesIndexRoute
  '/nehub-53ff1f11/produits/': typeof Nehub53ff1f11ProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/facture/$id': typeof FactureIdRoute
  '/nehub-53ff1f11/avis': typeof Nehub53ff1f11AvisRoute
  '/nehub-53ff1f11/categories': typeof Nehub53ff1f11CategoriesRoute
  '/nehub-53ff1f11/codes-promo': typeof Nehub53ff1f11CodesPromoRoute
  '/nehub-53ff1f11/comptabilite': typeof Nehub53ff1f11ComptabiliteRoute
  '/nehub-53ff1f11/depenses': typeof Nehub53ff1f11DepensesRoute
  '/nehub-53ff1f11/parametres': typeof Nehub53ff1f11ParametresRoute
  '/nehub-53ff1f11/promotions': typeof Nehub53ff1f11PromotionsRoute
  '/nehub-53ff1f11/stocks': typeof Nehub53ff1f11StocksRoute
  '/nehub-53ff1f11/ventes-hors-site': typeof Nehub53ff1f11VentesHorsSiteRoute
  '/produit/$id': typeof ProduitIdRoute
  '/nehub-53ff1f11': typeof Nehub53ff1f11IndexRoute
  '/nehub-53ff1f11/commandes/$id': typeof Nehub53ff1f11CommandesIdRoute
  '/nehub-53ff1f11/produits/$id': typeof Nehub53ff1f11ProduitsIdRoute
  '/nehub-53ff1f11/produits/nouveau': typeof Nehub53ff1f11ProduitsNouveauRoute
  '/nehub-53ff1f11/commandes': typeof Nehub53ff1f11CommandesIndexRoute
  '/nehub-53ff1f11/produits': typeof Nehub53ff1f11ProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/favoris': typeof FavorisRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nehub-53ff1f11': typeof Nehub53ff1f11RouteWithChildren
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/facture/$id': typeof FactureIdRoute
  '/nehub-53ff1f11/avis': typeof Nehub53ff1f11AvisRoute
  '/nehub-53ff1f11/categories': typeof Nehub53ff1f11CategoriesRoute
  '/nehub-53ff1f11/codes-promo': typeof Nehub53ff1f11CodesPromoRoute
  '/nehub-53ff1f11/comptabilite': typeof Nehub53ff1f11ComptabiliteRoute
  '/nehub-53ff1f11/depenses': typeof Nehub53ff1f11DepensesRoute
  '/nehub-53ff1f11/parametres': typeof Nehub53ff1f11ParametresRoute
  '/nehub-53ff1f11/promotions': typeof Nehub53ff1f11PromotionsRoute
  '/nehub-53ff1f11/stocks': typeof Nehub53ff1f11StocksRoute
  '/nehub-53ff1f11/ventes-hors-site': typeof Nehub53ff1f11VentesHorsSiteRoute
  '/produit/$id': typeof ProduitIdRoute
  '/nehub-53ff1f11/': typeof Nehub53ff1f11IndexRoute
  '/nehub-53ff1f11/commandes/$id': typeof Nehub53ff1f11CommandesIdRoute
  '/nehub-53ff1f11/produits/$id': typeof Nehub53ff1f11ProduitsIdRoute
  '/nehub-53ff1f11/produits/nouveau': typeof Nehub53ff1f11ProduitsNouveauRoute
  '/nehub-53ff1f11/commandes/': typeof Nehub53ff1f11CommandesIndexRoute
  '/nehub-53ff1f11/produits/': typeof Nehub53ff1f11ProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/commande'
    | '/confidentialite'
    | '/favoris'
    | '/mentions-legales'
    | '/nehub-53ff1f11'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/suivi-commande'
    | '/facture/$id'
    | '/nehub-53ff1f11/avis'
    | '/nehub-53ff1f11/categories'
    | '/nehub-53ff1f11/codes-promo'
    | '/nehub-53ff1f11/comptabilite'
    | '/nehub-53ff1f11/depenses'
    | '/nehub-53ff1f11/parametres'
    | '/nehub-53ff1f11/promotions'
    | '/nehub-53ff1f11/stocks'
    | '/nehub-53ff1f11/ventes-hors-site'
    | '/produit/$id'
    | '/nehub-53ff1f11/'
    | '/nehub-53ff1f11/commandes/$id'
    | '/nehub-53ff1f11/produits/$id'
    | '/nehub-53ff1f11/produits/nouveau'
    | '/nehub-53ff1f11/commandes/'
    | '/nehub-53ff1f11/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/commande'
    | '/confidentialite'
    | '/favoris'
    | '/mentions-legales'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/suivi-commande'
    | '/facture/$id'
    | '/nehub-53ff1f11/avis'
    | '/nehub-53ff1f11/categories'
    | '/nehub-53ff1f11/codes-promo'
    | '/nehub-53ff1f11/comptabilite'
    | '/nehub-53ff1f11/depenses'
    | '/nehub-53ff1f11/parametres'
    | '/nehub-53ff1f11/promotions'
    | '/nehub-53ff1f11/stocks'
    | '/nehub-53ff1f11/ventes-hors-site'
    | '/produit/$id'
    | '/nehub-53ff1f11'
    | '/nehub-53ff1f11/commandes/$id'
    | '/nehub-53ff1f11/produits/$id'
    | '/nehub-53ff1f11/produits/nouveau'
    | '/nehub-53ff1f11/commandes'
    | '/nehub-53ff1f11/produits'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/commande'
    | '/confidentialite'
    | '/favoris'
    | '/mentions-legales'
    | '/nehub-53ff1f11'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/suivi-commande'
    | '/facture/$id'
    | '/nehub-53ff1f11/avis'
    | '/nehub-53ff1f11/categories'
    | '/nehub-53ff1f11/codes-promo'
    | '/nehub-53ff1f11/comptabilite'
    | '/nehub-53ff1f11/depenses'
    | '/nehub-53ff1f11/parametres'
    | '/nehub-53ff1f11/promotions'
    | '/nehub-53ff1f11/stocks'
    | '/nehub-53ff1f11/ventes-hors-site'
    | '/produit/$id'
    | '/nehub-53ff1f11/'
    | '/nehub-53ff1f11/commandes/$id'
    | '/nehub-53ff1f11/produits/$id'
    | '/nehub-53ff1f11/produits/nouveau'
    | '/nehub-53ff1f11/commandes/'
    | '/nehub-53ff1f11/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CommandeRoute: typeof CommandeRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  FavorisRoute: typeof FavorisRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  Nehub53ff1f11Route: typeof Nehub53ff1f11RouteWithChildren
  PanierRoute: typeof PanierRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  SuiviCommandeRoute: typeof SuiviCommandeRoute
  FactureIdRoute: typeof FactureIdRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nehub-53ff1f11': {
      id: '/nehub-53ff1f11'
      path: '/nehub-53ff1f11'
      fullPath: '/nehub-53ff1f11'
      preLoaderRoute: typeof Nehub53ff1f11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi-commande': {
      id: '/suivi-commande'
      path: '/suivi-commande'
      fullPath: '/suivi-commande'
      preLoaderRoute: typeof SuiviCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facture/$id': {
      id: '/facture/$id'
      path: '/facture/$id'
      fullPath: '/facture/$id'
      preLoaderRoute: typeof FactureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nehub-53ff1f11/': {
      id: '/nehub-53ff1f11/'
      path: '/'
      fullPath: '/nehub-53ff1f11/'
      preLoaderRoute: typeof Nehub53ff1f11IndexRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/avis': {
      id: '/nehub-53ff1f11/avis'
      path: '/avis'
      fullPath: '/nehub-53ff1f11/avis'
      preLoaderRoute: typeof Nehub53ff1f11AvisRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/categories': {
      id: '/nehub-53ff1f11/categories'
      path: '/categories'
      fullPath: '/nehub-53ff1f11/categories'
      preLoaderRoute: typeof Nehub53ff1f11CategoriesRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/codes-promo': {
      id: '/nehub-53ff1f11/codes-promo'
      path: '/codes-promo'
      fullPath: '/nehub-53ff1f11/codes-promo'
      preLoaderRoute: typeof Nehub53ff1f11CodesPromoRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/comptabilite': {
      id: '/nehub-53ff1f11/comptabilite'
      path: '/comptabilite'
      fullPath: '/nehub-53ff1f11/comptabilite'
      preLoaderRoute: typeof Nehub53ff1f11ComptabiliteRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/depenses': {
      id: '/nehub-53ff1f11/depenses'
      path: '/depenses'
      fullPath: '/nehub-53ff1f11/depenses'
      preLoaderRoute: typeof Nehub53ff1f11DepensesRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/parametres': {
      id: '/nehub-53ff1f11/parametres'
      path: '/parametres'
      fullPath: '/nehub-53ff1f11/parametres'
      preLoaderRoute: typeof Nehub53ff1f11ParametresRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/promotions': {
      id: '/nehub-53ff1f11/promotions'
      path: '/promotions'
      fullPath: '/nehub-53ff1f11/promotions'
      preLoaderRoute: typeof Nehub53ff1f11PromotionsRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/stocks': {
      id: '/nehub-53ff1f11/stocks'
      path: '/stocks'
      fullPath: '/nehub-53ff1f11/stocks'
      preLoaderRoute: typeof Nehub53ff1f11StocksRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/ventes-hors-site': {
      id: '/nehub-53ff1f11/ventes-hors-site'
      path: '/ventes-hors-site'
      fullPath: '/nehub-53ff1f11/ventes-hors-site'
      preLoaderRoute: typeof Nehub53ff1f11VentesHorsSiteRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nehub-53ff1f11/commandes/': {
      id: '/nehub-53ff1f11/commandes/'
      path: '/commandes'
      fullPath: '/nehub-53ff1f11/commandes/'
      preLoaderRoute: typeof Nehub53ff1f11CommandesIndexRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/commandes/$id': {
      id: '/nehub-53ff1f11/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/nehub-53ff1f11/commandes/$id'
      preLoaderRoute: typeof Nehub53ff1f11CommandesIdRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/produits/': {
      id: '/nehub-53ff1f11/produits/'
      path: '/produits'
      fullPath: '/nehub-53ff1f11/produits/'
      preLoaderRoute: typeof Nehub53ff1f11ProduitsIndexRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/produits/$id': {
      id: '/nehub-53ff1f11/produits/$id'
      path: '/produits/$id'
      fullPath: '/nehub-53ff1f11/produits/$id'
      preLoaderRoute: typeof Nehub53ff1f11ProduitsIdRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
    '/nehub-53ff1f11/produits/nouveau': {
      id: '/nehub-53ff1f11/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/nehub-53ff1f11/produits/nouveau'
      preLoaderRoute: typeof Nehub53ff1f11ProduitsNouveauRouteImport
      parentRoute: typeof Nehub53ff1f11Route
    }
  }
}

interface Nehub53ff1f11RouteChildren {
  Nehub53ff1f11AvisRoute: typeof Nehub53ff1f11AvisRoute
  Nehub53ff1f11CategoriesRoute: typeof Nehub53ff1f11CategoriesRoute
  Nehub53ff1f11CodesPromoRoute: typeof Nehub53ff1f11CodesPromoRoute
  Nehub53ff1f11ComptabiliteRoute: typeof Nehub53ff1f11ComptabiliteRoute
  Nehub53ff1f11DepensesRoute: typeof Nehub53ff1f11DepensesRoute
  Nehub53ff1f11ParametresRoute: typeof Nehub53ff1f11ParametresRoute
  Nehub53ff1f11PromotionsRoute: typeof Nehub53ff1f11PromotionsRoute
  Nehub53ff1f11StocksRoute: typeof Nehub53ff1f11StocksRoute
  Nehub53ff1f11VentesHorsSiteRoute: typeof Nehub53ff1f11VentesHorsSiteRoute
  Nehub53ff1f11IndexRoute: typeof Nehub53ff1f11IndexRoute
  Nehub53ff1f11CommandesIdRoute: typeof Nehub53ff1f11CommandesIdRoute
  Nehub53ff1f11ProduitsIdRoute: typeof Nehub53ff1f11ProduitsIdRoute
  Nehub53ff1f11ProduitsNouveauRoute: typeof Nehub53ff1f11ProduitsNouveauRoute
  Nehub53ff1f11CommandesIndexRoute: typeof Nehub53ff1f11CommandesIndexRoute
  Nehub53ff1f11ProduitsIndexRoute: typeof Nehub53ff1f11ProduitsIndexRoute
}

const Nehub53ff1f11RouteChildren: Nehub53ff1f11RouteChildren = {
  Nehub53ff1f11AvisRoute: Nehub53ff1f11AvisRoute,
  Nehub53ff1f11CategoriesRoute: Nehub53ff1f11CategoriesRoute,
  Nehub53ff1f11CodesPromoRoute: Nehub53ff1f11CodesPromoRoute,
  Nehub53ff1f11ComptabiliteRoute: Nehub53ff1f11ComptabiliteRoute,
  Nehub53ff1f11DepensesRoute: Nehub53ff1f11DepensesRoute,
  Nehub53ff1f11ParametresRoute: Nehub53ff1f11ParametresRoute,
  Nehub53ff1f11PromotionsRoute: Nehub53ff1f11PromotionsRoute,
  Nehub53ff1f11StocksRoute: Nehub53ff1f11StocksRoute,
  Nehub53ff1f11VentesHorsSiteRoute: Nehub53ff1f11VentesHorsSiteRoute,
  Nehub53ff1f11IndexRoute: Nehub53ff1f11IndexRoute,
  Nehub53ff1f11CommandesIdRoute: Nehub53ff1f11CommandesIdRoute,
  Nehub53ff1f11ProduitsIdRoute: Nehub53ff1f11ProduitsIdRoute,
  Nehub53ff1f11ProduitsNouveauRoute: Nehub53ff1f11ProduitsNouveauRoute,
  Nehub53ff1f11CommandesIndexRoute: Nehub53ff1f11CommandesIndexRoute,
  Nehub53ff1f11ProduitsIndexRoute: Nehub53ff1f11ProduitsIndexRoute,
}

const Nehub53ff1f11RouteWithChildren = Nehub53ff1f11Route._addFileChildren(
  Nehub53ff1f11RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRoute,
  CommandeRoute: CommandeRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  FavorisRoute: FavorisRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  Nehub53ff1f11Route: Nehub53ff1f11RouteWithChildren,
  PanierRoute: PanierRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  SuiviCommandeRoute: SuiviCommandeRoute,
  FactureIdRoute: FactureIdRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
