/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminStocksRouteImport } from './routes/admin.stocks'
import { Route as FactureIdRouteImport } from './routes/facture.$id'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index'
import { Route as AdminCommandesIdRouteImport } from './routes/admin.commandes.$id'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin.produits.index'
import { Route as AdminProduitsIdRouteImport } from './routes/admin.produits.$id'
import { Route as AdminProduitsNouveauRouteImport } from './routes/admin.produits.nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocksRoute = AdminStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AdminRoute,
} as any)
const FactureIdRoute = FactureIdRouteImport.update({
  id: '/facture/$id',
  path: '/facture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesIdRoute = AdminCommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsIdRoute = AdminProduitsIdRouteImport.update({
  id: '/produits/$id',
  path: '/produits/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsNouveauRoute = AdminProduitsNouveauRouteImport.update({
  id: '/produits/nouveau',
  path: '/produits/nouveau',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/facture/$id': typeof FactureIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/facture/$id': typeof FactureIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/admin/commandes': typeof AdminCommandesIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/stocks': typeof AdminStocksRoute
  '/facture/$id': typeof FactureIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/produits/$id': typeof AdminProduitsIdRoute
  '/admin/produits/nouveau': typeof AdminProduitsNouveauRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/commande'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/stocks'
    | '/facture/$id'
    | '/produit/$id'
    | '/admin/'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/admin/commandes/'
    | '/admin/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/commande'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/stocks'
    | '/facture/$id'
    | '/produit/$id'
    | '/admin'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/admin/commandes'
    | '/admin/produits'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/commande'
    | '/panier'
    | '/reinitialiser-mot-de-passe'
    | '/admin/parametres'
    | '/admin/promotions'
    | '/admin/stocks'
    | '/facture/$id'
    | '/produit/$id'
    | '/admin/'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/admin/produits/nouveau'
    | '/admin/commandes/'
    | '/admin/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRoute
  CommandeRoute: typeof CommandeRoute
  PanierRoute: typeof PanierRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  FactureIdRoute: typeof FactureIdRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stocks': {
      id: '/admin/stocks'
      path: '/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/facture/$id': {
      id: '/facture/$id'
      path: '/facture/$id'
      fullPath: '/facture/$id'
      preLoaderRoute: typeof FactureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commandes/': {
      id: '/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AdminCommandesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes/$id': {
      id: '/admin/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/admin/commandes/$id'
      preLoaderRoute: typeof AdminCommandesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits/'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/$id': {
      id: '/admin/produits/$id'
      path: '/produits/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AdminProduitsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/nouveau': {
      id: '/admin/produits/nouveau'
      path: '/produits/nouveau'
      fullPath: '/admin/produits/nouveau'
      preLoaderRoute: typeof AdminProduitsNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminStocksRoute: typeof AdminStocksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommandesIdRoute: typeof AdminCommandesIdRoute
  AdminProduitsIdRoute: typeof AdminProduitsIdRoute
  AdminProduitsNouveauRoute: typeof AdminProduitsNouveauRoute
  AdminCommandesIndexRoute: typeof AdminCommandesIndexRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminParametresRoute: AdminParametresRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminStocksRoute: AdminStocksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommandesIdRoute: AdminCommandesIdRoute,
  AdminProduitsIdRoute: AdminProduitsIdRoute,
  AdminProduitsNouveauRoute: AdminProduitsNouveauRoute,
  AdminCommandesIndexRoute: AdminCommandesIndexRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BoutiqueRoute: BoutiqueRoute,
  CommandeRoute: CommandeRoute,
  PanierRoute: PanierRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  FactureIdRoute: FactureIdRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
